2025-01-14 16:42:57,537 - CIFAR_learning_rate - INFO - Starting hyperparameter tuning experiment
2025-01-14 16:42:57,537 - CIFAR_learning_rate - INFO - Testing learning rates: [0.005, 0.001, 0.0005, 0.0001]
2025-01-14 16:42:57,601 - CIFAR_learning_rate - INFO - Starting Run 3/5
2025-01-14 16:42:57,601 - CIFAR_learning_rate - INFO - Starting tuning for: 0.005
2025-01-14 16:42:58,476 - CIFAR_learning_rate - INFO - Starting server type: local
Traceback (most recent call last):
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/run.py", line 38, in <module>
    main()
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/run.py", line 31, in main
    run_experiments(args.dataset, experiment_type)
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/run.py", line 11, in run_experiments
    return experiment.run_experiment()
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/pipeline.py", line 120, in run_experiment
    return self._run_hyperparameter_tuning()
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/pipeline.py", line 169, in _run_hyperparameter_tuning
    self._hyperparameter_tuning(hyperparams, remaining_server_types)
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/pipeline.py", line 194, in _hyperparameter_tuning
    metrics = self._train_and_evaluate(server, server.config.rounds)
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/pipeline.py", line 351, in _train_and_evaluate
    server.train_round()
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/servers.py", line 66, in train_round
    client_train_loss = client.train(self.personal)
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/clients.py", line 186, in train
    final_loss = self.train_epoch(personal)
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/clients.py", line 161, in train_epoch
    for batch_x, batch_y in self.data.train_loader:
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gpfs/commons/groups/gursoy_lab/aelhussein/layer_pfl/code/dataset_processing.py", line 229, in __getitem__
    image_tensor = self.transform(image)
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 234, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/gpfs/commons/home/aelhussein/anaconda3/envs/cuda_env_ne1/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 277, in to_pil_image
    raise ValueError(f"pic should not have > 4 channels. Got {pic.shape[-1]} channels.")
ValueError: pic should not have > 4 channels. Got 32 channels.
